public class ExceptionExample {

    publicity static void main(String[] args) {
        int a = 10;
        int b = 0;

        // ArithmeticException
        try {
            int c = a / b;
        } catch (ArithmeticException e) {
            System.out.println("ArithmeticException caught: " + e.getMessage());
        }

        // ArrayIndexOutOfBoundsException
        int[] arr = new int[3];
        try {
            arr[3] = 1;
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("ArrayIndexOutOfBoundsException caught: " + e.getMessage());
        }
    }

}
